// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fskofgeiwqlhoouxjrsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZza29mZ2Vpd3FsaG9vdXhqcnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODIxODAsImV4cCI6MjA2ODI1ODE4MH0.fvniHf8rzS0yRbri9ELVvOasIC3LoOxbKJZIaNWDaBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});